import '../models/meal_plan_model.dart';

class MealService {
  static final List<MealPlanModel> _mealPlans = [
    MealPlanModel(
      id: '1',
      name: 'Beginner Weight Loss Program',
      description: 'Perfect for beginners looking to lose weight and build healthy habits.',
      category: 'Weight Loss',
      totalCalories: 1800,
      totalProtein: 120,
      totalCarbs: 150,
      totalFat: 60,
      meals: [
        MealModel(
          id: '1',
          name: 'Protein Breakfast Bowl',
          type: 'breakfast',
          calories: 300,
          protein: 25,
          carbs: 30,
          fat: 8,
          foodItems: [
            FoodItemModel(
              id: '1',
              name: 'Oatmeal',
              quantity: 50,
              unit: 'g',
              calories: 150,
              protein: 5,
              carbs: 27,
              fat: 3,
            ),
            FoodItemModel(
              id: '2',
              name: 'Boiled Eggs',
              quantity: 2,
              unit: 'pieces',
              calories: 70,
              protein: 6,
              carbs: 1,
              fat: 5,
            ),
            FoodItemModel(
              id: '3',
              name: 'Banana',
              quantity: 1,
              unit: 'medium',
              calories: 80,
              protein: 1,
              carbs: 20,
              fat: 0,
            ),
          ],
        ),
        MealModel(
          id: '2',
          name: 'Grilled Chicken Salad',
          type: 'lunch',
          calories: 450,
          protein: 35,
          carbs: 25,
          fat: 15,
          foodItems: [
            FoodItemModel(
              id: '4',
              name: 'Grilled Chicken Breast',
              quantity: 120,
              unit: 'g',
              calories: 200,
              protein: 30,
              carbs: 0,
              fat: 5,
            ),
            FoodItemModel(
              id: '5',
              name: 'Mixed Greens',
              quantity: 50,
              unit: 'g',
              calories: 25,
              protein: 2,
              carbs: 5,
              fat: 0,
            ),
            FoodItemModel(
              id: '6',
              name: 'Olive Oil',
              quantity: 15,
              unit: 'ml',
              calories: 135,
              protein: 0,
              carbs: 0,
              fat: 15,
            ),
          ],
        ),
        MealModel(
          id: '3',
          name: 'Salmon with Vegetables',
          type: 'dinner',
          calories: 550,
          protein: 40,
          carbs: 35,
          fat: 25,
          foodItems: [
            FoodItemModel(
              id: '7',
              name: 'Salmon Fillet',
              quantity: 150,
              unit: 'g',
              calories: 300,
              protein: 35,
              carbs: 0,
              fat: 15,
            ),
            FoodItemModel(
              id: '8',
              name: 'Brown Rice',
              quantity: 100,
              unit: 'g',
              calories: 150,
              protein: 3,
              carbs: 30,
              fat: 1,
            ),
            FoodItemModel(
              id: '9',
              name: 'Steamed Broccoli',
              quantity: 100,
              unit: 'g',
              calories: 55,
              protein: 4,
              carbs: 10,
              fat: 1,
            ),
          ],
        ),
      ],
      difficulty: 'Easy',
      duration: 7,
      isFavorite: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    MealPlanModel(
      id: '2',
      name: 'Muscle Gain Program',
      description: 'Ideal for those looking to build muscle and strength.',
      category: 'Muscle Gain',
      totalCalories: 2200,
      totalProtein: 150,
      totalCarbs: 200,
      totalFat: 70,
      meals: [
        MealModel(
          id: '4',
          name: 'Protein Pancakes',
          type: 'breakfast',
          calories: 400,
          protein: 30,
          carbs: 45,
          fat: 12,
          foodItems: [
            FoodItemModel(
              id: '10',
              name: 'Protein Powder',
              quantity: 30,
              unit: 'g',
              calories: 120,
              protein: 25,
              carbs: 3,
              fat: 1,
            ),
            FoodItemModel(
              id: '11',
              name: 'Oats',
              quantity: 60,
              unit: 'g',
              calories: 200,
              protein: 7,
              carbs: 35,
              fat: 4,
            ),
            FoodItemModel(
              id: '12',
              name: 'Eggs',
              quantity: 2,
              unit: 'pieces',
              calories: 140,
              protein: 12,
              carbs: 1,
              fat: 10,
            ),
          ],
        ),
        MealModel(
          id: '5',
          name: 'Beef and Rice Bowl',
          type: 'lunch',
          calories: 600,
          protein: 45,
          carbs: 60,
          fat: 20,
          foodItems: [
            FoodItemModel(
              id: '13',
              name: 'Lean Beef',
              quantity: 150,
              unit: 'g',
              calories: 300,
              protein: 35,
              carbs: 0,
              fat: 15,
            ),
            FoodItemModel(
              id: '14',
              name: 'White Rice',
              quantity: 150,
              unit: 'g',
              calories: 200,
              protein: 4,
              carbs: 45,
              fat: 0,
            ),
            FoodItemModel(
              id: '15',
              name: 'Mixed Vegetables',
              quantity: 100,
              unit: 'g',
              calories: 100,
              protein: 6,
              carbs: 15,
              fat: 5,
            ),
          ],
        ),
      ],
      difficulty: 'Medium',
      duration: 14,
      isFavorite: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    MealPlanModel(
      id: '3',
      name: 'Cardio Fitness Program',
      description: 'Ideal for those looking to improve cardiovascular health.',
      category: 'Cardio',
      totalCalories: 1500,
      totalProtein: 100,
      totalCarbs: 180,
      totalFat: 50,
      meals: [
        MealModel(
          id: '6',
          name: 'Energy Breakfast',
          type: 'breakfast',
          calories: 300,
          protein: 20,
          carbs: 45,
          fat: 8,
          foodItems: [
            FoodItemModel(
              id: '16',
              name: 'Greek Yogurt',
              quantity: 150,
              unit: 'g',
              calories: 120,
              protein: 15,
              carbs: 8,
              fat: 3,
            ),
            FoodItemModel(
              id: '17',
              name: 'Berries',
              quantity: 100,
              unit: 'g',
              calories: 60,
              protein: 1,
              carbs: 15,
              fat: 0,
            ),
            FoodItemModel(
              id: '18',
              name: 'Granola',
              quantity: 30,
              unit: 'g',
              calories: 120,
              protein: 4,
              carbs: 22,
              fat: 5,
            ),
          ],
        ),
        MealModel(
          id: '7',
          name: 'Light Tuna Salad',
          type: 'lunch',
          calories: 350,
          protein: 30,
          carbs: 25,
          fat: 12,
          foodItems: [
            FoodItemModel(
              id: '19',
              name: 'Tuna',
              quantity: 100,
              unit: 'g',
              calories: 150,
              protein: 25,
              carbs: 0,
              fat: 5,
            ),
            FoodItemModel(
              id: '20',
              name: 'Mixed Salad',
              quantity: 100,
              unit: 'g',
              calories: 50,
              protein: 3,
              carbs: 10,
              fat: 0,
            ),
            FoodItemModel(
              id: '21',
              name: 'Olive Oil Dressing',
              quantity: 10,
              unit: 'ml',
              calories: 90,
              protein: 0,
              carbs: 0,
              fat: 10,
            ),
          ],
        ),
      ],
      difficulty: 'Easy',
      duration: 7,
      isFavorite: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static List<MealPlanModel> get mealPlans => _mealPlans;
}